### ISSUE TITLE
Is there a workaround?

### ISSUE THREAD

**Issue by ghost** [artur-deluca/landscapeviz#8]
import resource
ModuleNotFoundError: No module named 'resource'

I know resource is for unix and I have windows 10. I don't know how to resolve this issue?

**Comment by artur-deluca** [comment]
Hey @DominicHJ45, thanks for pointing this out. I think it was a dangling import. It should be fixed now https://github.com/artur-deluca/landscapeviz/pull/10 

Have fun!
